/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    articles: Article;
    specialists: Specialist;
    faqs: Faq;
    testimonials: Testimonial;
    'landing-pages': LandingPage;
    'demo-requests': DemoRequest;
    'brand-profiles': BrandProfile;
    'social-assets': SocialAsset;
    'social-posts': SocialPost;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    specialists: SpecialistsSelect<false> | SpecialistsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'landing-pages': LandingPagesSelect<false> | LandingPagesSelect<true>;
    'demo-requests': DemoRequestsSelect<false> | DemoRequestsSelect<true>;
    'brand-profiles': BrandProfilesSelect<false> | BrandProfilesSelect<true>;
    'social-assets': SocialAssetsSelect<false> | SocialAssetsSelect<true>;
    'social-posts': SocialPostsSelect<false> | SocialPostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es') | ('en' | 'es')[];
  globals: {
    'linkedin-connection': LinkedinConnection;
  };
  globalsSelect: {
    'linkedin-connection': LinkedinConnectionSelect<false> | LinkedinConnectionSelect<true>;
  };
  locale: 'en' | 'es';
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  heroHeadline?: string | null;
  heroSubheadline?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  category?: ('sinus-health' | 'treatment-options' | 'patient-stories' | 'news') | null;
  publishedDate?: string | null;
  author?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialists".
 */
export interface Specialist {
  id: number;
  name: string;
  /**
   * e.g., MD, FACS
   */
  credentials?: string | null;
  practiceName: string;
  specialties?:
    | {
        specialty?: string | null;
        id?: string | null;
      }[]
    | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photo?: (number | null) | Media;
  phone: string;
  email?: string | null;
  address: {
    street?: string | null;
    city: string;
    state: string;
    zip?: string | null;
  };
  /**
   * Location identifier for filtering (e.g., raleigh-nc, savannah-ga)
   */
  location?: string | null;
  /**
   * HubSpot form ID for contact form
   */
  hubspotFormId?: string | null;
  website?: string | null;
  acceptingNewPatients?: boolean | null;
  /**
   * Show on homepage
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: ('general' | 'balloon-sinuplasty' | 'treatment' | 'insurance' | 'recovery') | null;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  /**
   * City, State
   */
  location?: string | null;
  type?: ('video' | 'text') | null;
  content?: string | null;
  /**
   * YouTube or Vimeo URL
   */
  videoUrl?: string | null;
  videoThumbnail?: (number | null) | Media;
  photo?: (number | null) | Media;
  rating?: number | null;
  /**
   * Associated specialist (optional)
   */
  specialist?: (number | null) | Specialist;
  /**
   * Show on homepage
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Location-specific ad landing pages
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages".
 */
export interface LandingPage {
  id: number;
  /**
   * URL path (e.g., raleigh-nc-sinus-treatment)
   */
  slug: string;
  /**
   * City name for display (e.g., Raleigh)
   */
  locationName: string;
  /**
   * Main headline with {location} placeholder
   */
  heroHeadline: string;
  heroSubheadline?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Local phone number to display
   */
  localPhone: string;
  /**
   * Specialists to show on this landing page
   */
  specialists: (number | Specialist)[];
  /**
   * FAQs to display on this page
   */
  faqs?: (number | Faq)[] | null;
  /**
   * Featured testimonial for this page
   */
  testimonial?: (number | null) | Testimonial;
  stats?: {
    patientsHelped?: string | null;
    successRate?: string | null;
    yearsExperience?: string | null;
    specialistsCount?: string | null;
  };
  /**
   * Connect, Treat, Breathe section
   */
  threeSteps?: {
    step1Title?: string | null;
    step1Description?: string | null;
    step2Title?: string | null;
    step2Description?: string | null;
    step3Title?: string | null;
    step3Description?: string | null;
  };
  /**
   * Analytics and tracking IDs
   */
  tracking?: {
    googleAnalyticsId?: string | null;
    facebookPixelId?: string | null;
    excelVoiceId?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Submissions from the B2B "Request a Demo" form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demo-requests".
 */
export interface DemoRequest {
  id: number;
  name: string;
  email: string;
  practice: string;
  role: string;
  providers?: string | null;
  phone?: string | null;
  emr?: string | null;
  rcm?: string | null;
  pain?: string | null;
  userAgent?: string | null;
  ip?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * One editable "agent" per product: voice, audience, themes, CTAs, and guardrails.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-profiles".
 */
export interface BrandProfile {
  id: number;
  /**
   * e.g. "PS | RCM"
   */
  name: string;
  /**
   * Lowercase id, e.g. "ps-rcm". Used by the generator.
   */
  slug: string;
  active?: boolean | null;
  reviewers?:
    | {
        email: string
        id?: string | null
      }[]
    | null
  /**
   * Voice and tone guidance the writer must follow.
   */
  voice: string;
  /**
   * Who these posts are for.
   */
  audience?: string | null;
  /**
   * Content pillars the generator can write about.
   */
  themes?:
    | {
        theme: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  defaultCtas?:
    | {
        cta: string;
        id?: string | null;
      }[]
    | null;
  platforms?: ('linkedin' | 'facebook' | 'instagram')[] | null;
  /**
   * Free text for now, e.g. "3 posts/week". Guidance only in Phase A.
   */
  cadence?: string | null;
  /**
   * Words/phrases that must never appear. Compliance guardrail.
   */
  bannedTerms?:
    | {
        term: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Text that must appear verbatim in every post.
   */
  requiredDisclaimers?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * A few example posts that anchor the brand style.
   */
  seedExamples?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Approved images for social posts, tagged by brand and theme.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-assets".
 */
export interface SocialAsset {
  id: number;
  /**
   * Accessibility text / internal label.
   */
  alt: string;
  /**
   * Leave empty to make the asset usable by any brand.
   */
  brand?: (number | null) | BrandProfile;
  /**
   * Theme tags the generator matches against (e.g. "Denials").
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * AI-generated is a future source; everything is uploaded in Phase A.
   */
  source?: ('uploaded' | 'ai-generated') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    preview?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * AI-drafted posts. Review, edit, approve/reject here — your feedback trains the next batch.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-posts".
 */
export interface SocialPost {
  id: number;
  /**
   * Short label; auto-filled by the generator, editable.
   */
  title?: string | null;
  brand: number | BrandProfile;
  platform: 'linkedin' | 'facebook' | 'instagram';
  language?: ('en' | 'es') | null;
  theme?: string | null;
  /**
   * The post text. Edit freely before approving.
   */
  copy: string;
  cta?: string | null;
  asset?: (number | null) | SocialAsset;
  /**
   * Which generated graphic to render. The generator suggests one.
   */
  graphicStyle?: ('none' | 'hook' | 'stat' | 'dataviz') | null;
  /**
   * Text rendered onto the graphic. Pre-filled by the generator; edit freely.
   */
  graphic?: {
    /**
     * Hook/main line (hook card).
     */
    headline?: string | null;
    /**
     * Supporting line (stat hero).
     */
    subtext?: string | null;
    /**
     * e.g. "11.8%" — stat/data-viz.
     */
    statFrom?: string | null;
    /**
     * e.g. "2.5%" — stat/data-viz.
     */
    statTo?: string | null;
    /**
     * e.g. "ENT Denial Rate".
     */
    statLabel?: string | null;
    /**
     * Small footer line (data-viz).
     */
    caption?: string | null;
  };
  /**
   * Set to Approved when ready, or leave feedback and set Needs changes / Rejected.
   */
  status: 'draft' | 'needs-changes' | 'approved' | 'rejected';
  /**
   * Why it needs changes or was rejected. This text trains the next generation.
   */
  reviewerFeedback?: string | null;
  scheduledTime?: string | null;
  publish?: {
    state?: ('pending' | 'scheduled' | 'publishing' | 'sent' | 'failed') | null;
    postUrn?: string | null;
    sentAt?: string | null;
    error?: string | null;
    attempts?: number | null;
  };
  /**
   * Provenance — read only.
   */
  generationMeta?: {
    model?: string | null;
    promptVersion?: string | null;
    /**
     * Copy as generated, before edits.
     */
    originalCopy?: string | null;
    /**
     * Non-empty means a banned term or missing disclaimer — review before approving.
     */
    guardrailFlags?: string | null;
  };
  notify?: {
    generatedAt?: string | null
    reviewSentAt?: string | null
    reminderSentAt?: string | null
    publishedNotifiedAt?: string | null
  }
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'specialists';
        value: number | Specialist;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'landing-pages';
        value: number | LandingPage;
      } | null)
    | ({
        relationTo: 'demo-requests';
        value: number | DemoRequest;
      } | null)
    | ({
        relationTo: 'brand-profiles';
        value: number | BrandProfile;
      } | null)
    | ({
        relationTo: 'social-assets';
        value: number | SocialAsset;
      } | null)
    | ({
        relationTo: 'social-posts';
        value: number | SocialPost;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  heroImage?: T;
  heroHeadline?: T;
  heroSubheadline?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  category?: T;
  publishedDate?: T;
  author?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialists_select".
 */
export interface SpecialistsSelect<T extends boolean = true> {
  name?: T;
  credentials?: T;
  practiceName?: T;
  specialties?:
    | T
    | {
        specialty?: T;
        id?: T;
      };
  bio?: T;
  photo?: T;
  phone?: T;
  email?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  location?: T;
  hubspotFormId?: T;
  website?: T;
  acceptingNewPatients?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  location?: T;
  type?: T;
  content?: T;
  videoUrl?: T;
  videoThumbnail?: T;
  photo?: T;
  rating?: T;
  specialist?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages_select".
 */
export interface LandingPagesSelect<T extends boolean = true> {
  slug?: T;
  locationName?: T;
  heroHeadline?: T;
  heroSubheadline?: T;
  heroImage?: T;
  localPhone?: T;
  specialists?: T;
  faqs?: T;
  testimonial?: T;
  stats?:
    | T
    | {
        patientsHelped?: T;
        successRate?: T;
        yearsExperience?: T;
        specialistsCount?: T;
      };
  threeSteps?:
    | T
    | {
        step1Title?: T;
        step1Description?: T;
        step2Title?: T;
        step2Description?: T;
        step3Title?: T;
        step3Description?: T;
      };
  tracking?:
    | T
    | {
        googleAnalyticsId?: T;
        facebookPixelId?: T;
        excelVoiceId?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demo-requests_select".
 */
export interface DemoRequestsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  practice?: T;
  role?: T;
  providers?: T;
  phone?: T;
  emr?: T;
  rcm?: T;
  pain?: T;
  userAgent?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-profiles_select".
 */
export interface BrandProfilesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  active?: T;
  reviewers?:
    | T
    | {
        email?: T
        id?: T
      };
  voice?: T;
  audience?: T;
  themes?:
    | T
    | {
        theme?: T;
        description?: T;
        id?: T;
      };
  defaultCtas?:
    | T
    | {
        cta?: T;
        id?: T;
      };
  platforms?: T;
  cadence?: T;
  bannedTerms?:
    | T
    | {
        term?: T;
        id?: T;
      };
  requiredDisclaimers?:
    | T
    | {
        text?: T;
        id?: T;
      };
  seedExamples?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-assets_select".
 */
export interface SocialAssetsSelect<T extends boolean = true> {
  alt?: T;
  brand?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  source?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        preview?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-posts_select".
 */
export interface SocialPostsSelect<T extends boolean = true> {
  title?: T;
  brand?: T;
  platform?: T;
  language?: T;
  theme?: T;
  copy?: T;
  cta?: T;
  asset?: T;
  status?: T;
  reviewerFeedback?: T;
  scheduledTime?: T;
  publish?:
    | T
    | {
        state?: T;
        postUrn?: T;
        sentAt?: T;
        error?: T;
        attempts?: T;
      };
  generationMeta?:
    | T
    | {
        model?: T;
        promptVersion?: T;
        originalCopy?: T;
        guardrailFlags?: T;
      };
  notify?:
    | T
    | {
        generatedAt?: T
        reviewSentAt?: T
        reminderSentAt?: T
        publishedNotifiedAt?: T
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "linkedin-connection".
 */
export interface LinkedinConnection {
  id: number;
  /**
   * Connected organization URN.
   */
  orgUrn?: string | null;
  accessToken?: string | null;
  refreshToken?: string | null;
  accessExpiresAt?: string | null;
  refreshExpiresAt?: string | null;
  connectedBy?: (number | null) | User;
  connectedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "linkedin-connection_select".
 */
export interface LinkedinConnectionSelect<T extends boolean = true> {
  orgUrn?: T;
  accessToken?: T;
  refreshToken?: T;
  accessExpiresAt?: T;
  refreshExpiresAt?: T;
  connectedBy?: T;
  connectedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}